import { Employee, Job } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'e1',
    name: 'Maria Garcia',
    role: 'Deep Cleaning Specialist',
    location: { lat: 40.7128, lng: -74.006, address: 'Lower Manhattan, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
  {
    id: 'e2',
    name: 'David Wilson',
    role: 'Window Cleaning Expert',
    location: { lat: 40.7589, lng: -73.9851, address: 'Times Square, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: 'e3',
    name: 'Sarah Jenkins',
    role: 'Residential Cleaner',
    location: { lat: 40.7829, lng: -73.9654, address: 'Central Park, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SarahJ',
  },
  {
    id: 'e4',
    name: 'Robert Taylor',
    role: 'Commercial Janitor',
    location: { lat: 40.7484, lng: -73.9857, address: 'Empire State Building, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
  },
  {
    id: 'e5',
    name: 'Michael Chen',
    role: 'Floor Care Specialist',
    location: { lat: 40.6782, lng: -73.9442, address: 'Brooklyn, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: 'e6',
    name: 'Elena Rodriguez',
    role: 'Sanitization Expert',
    location: { lat: 40.7282, lng: -73.9942, address: 'Greenwich Village, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elena',
  },
  {
    id: 'e7',
    name: 'James Miller',
    role: 'Residential Lead',
    location: { lat: 40.7736, lng: -73.9566, address: 'Upper East Side, NY' },
    status: 'available',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Post-Construction Cleanup',
    description: 'Full dust removal and floor polishing for a new 3-bedroom apartment.',
    location: { lat: 40.7306, lng: -73.9352, address: 'Long Island City, NY' },
    status: 'unassigned',
    priority: 'high',
  },
  {
    id: 'j2',
    title: 'Weekly Office Cleaning',
    description: 'Standard cleaning of 15 workstations and breakroom.',
    location: { lat: 40.7061, lng: -74.0092, address: 'Wall Street, NY' },
    status: 'unassigned',
    priority: 'medium',
  },
  {
    id: 'j3',
    title: 'Move-Out Deep Clean',
    description: 'Thorough cleaning of kitchen appliances and bathroom sanitization.',
    location: { lat: 40.8075, lng: -73.9465, address: 'Harlem, NY' },
    status: 'unassigned',
    priority: 'high',
  },
  {
    id: 'j4',
    title: 'Exterior Window Washing',
    description: 'Ground floor storefront windows cleaning.',
    location: { lat: 40.7527, lng: -73.9772, address: 'Grand Central, NY' },
    status: 'unassigned',
    priority: 'low',
  },
  {
    id: 'j5',
    title: 'Carpet Steam Cleaning',
    description: 'Deep steam cleaning for a large living room and two bedrooms.',
    location: { lat: 40.6892, lng: -73.9712, address: 'Fort Greene, NY' },
    status: 'unassigned',
    priority: 'medium',
  },
  {
    id: 'j6',
    title: 'Kitchen Sanitization',
    description: 'Industrial-grade cleaning of restaurant kitchen surfaces and vents.',
    location: { lat: 40.7336, lng: -74.0027, address: 'West Village, NY' },
    status: 'unassigned',
    priority: 'high',
  },
  {
    id: 'j7',
    title: 'Medical Office Disinfection',
    description: 'Specialized sanitization for a 4-room dental clinic.',
    location: { lat: 40.7644, lng: -73.9744, address: 'Midtown East, NY' },
    status: 'unassigned',
    priority: 'high',
  },
  {
    id: 'j8',
    title: 'Airbnb Turnover',
    description: 'Quick turnover cleaning including linen change and restocking.',
    location: { lat: 40.7128, lng: -73.9626, address: 'Williamsburg, NY' },
    status: 'unassigned',
    priority: 'medium',
  },
  {
    id: 'j9',
    title: 'Retail Floor Waxing',
    description: 'Stripping and waxing of hardwood floors for a boutique.',
    location: { lat: 40.7233, lng: -74.0030, address: 'SoHo, NY' },
    status: 'unassigned',
    priority: 'low',
  },
  {
    id: 'j10',
    title: 'School Gym Deep Clean',
    description: 'Annual deep cleaning of gymnasium floors and equipment.',
    location: { lat: 40.7644, lng: -73.9235, address: 'Astoria, NY' },
    status: 'unassigned',
    priority: 'medium',
  },
];
